openapi: 3.1.0
info:
  version: 1.0.0
  title: Watertrack app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of my Watertrack app
tags:
  - name: Auth
    description: Authentication operations.
  - name: User
    description: Operation with user.
  - name: Water
    description: Operations related to tracking changes in water standards in the body.
servers:
  - url: https://waterapp-hfy2.onrender.com
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/auth/send-reset-email.yaml'
  /auth/reset-pwd:
    post:
      $ref: '../swagger/paths/auth/reset-pwd.yaml'
  /user/{id}:
    get:
      $ref: '../swagger/paths/user/{id}/get.yaml'
    put:
      $ref: '../swagger/paths/user/{id}/put.yaml'
    patch:
      $ref: '../swagger/paths/user/{id}/patch.yaml'
  /water/rate:
    patch:
      $ref: '../swagger/paths/water/rate.yaml'
  /water:
    post:
      $ref: '../swagger/paths/water/postWater.yaml'
  /water/{id}:
    patch:
      $ref: '../swagger/paths/water/{id}/patchWaterNoteId.yaml'
    delete:
      $ref: '../swagger/paths/water/{id}/deleteWaterNoteId.yaml'
  /water/today:
    get:
      $ref: '../swagger/paths/water/today.yaml'
  /water/month/:year/:month:
    get:
      $ref: '../swagger/paths/water/month.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
